### ISSUE TITLE
Error: cannot estimate gas

### ISSUE THREAD

**Issue by lysack** [idecentralize-finance/pulsar#1]
npx hardhat run-demo1

```
Initial DAI Balance :  3.0

An unexpected error occurred:

Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":3,"_isProviderError":true,"data": ..........
```

  reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',

**Comment by Madeindreams** [comment]
Try to raise the gas limit in the override argument of your task.

demo1.js

```
task(
  "run-demo1", 
  "Execute the demo1 sequence", 
  async (_, {network, ethers, upgrades }) => {
    let override = { gasLimit: 4000000 };    <-----------------------------
```

**Comment by lysack** [comment]
Might be an allowance issue.. 

    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  **error: ProviderError: execution reverted: ERC20: transfer amount exceeds allowance
      at HttpProvider.request** (/Users/lysack/dev/blockchain/pulsar/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
      at HDWalletProvider.request (/Users/lysack/dev/blockchain/pulsar/node_modules/hardhat/src/internal/core/providers/accounts.ts:187:34)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at EthersProviderWrapper.send (/Users/lysack/dev/blockchain/pulsar/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20),
  method: 'estimateGas',

**Comment by Madeindreams** [comment]
Yeas that's my fault again. Please un-comment the lines 52-53 in demo1


```
       let tx = await dai.approve(PULSAR, oneDai, override);   
       tx.wait(2)
```

**Comment by Madeindreams** [comment]
Will close this since everything is resolved
